language: objective-c
osx_image: xcode10
script:
  # The pipefail option sets the exit status to the last commond with a non-zero status code, which would usually be xcodebuild
  - set -o pipefail && xcodebuild test -project Example.xcodeproj -scheme SimpleButtonTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone x,OS=latest" | xcpretty
